apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: mcp-jwt-auth
  namespace: gateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: mcp-gateway
  jwtRules:
    - issuer: http://keycloak.127-0-0-1.sslip.io:8002/realms/mcp
      jwksUri: http://keycloak.keycloak.svc.cluster.local/realms/mcp/protocol/openid-connect/certs
      forwardOriginalToken: true
