apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: team-a-auth-server-a1
  namespace: team-a
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: test-server-a1
  rules:
    authentication:
      keycloak:
        jwt:
          issuerUrl: http://keycloak.127-0-0-1.sslip.io:8002/realms/mcp
    metadata:
      vault_token:
        http:
          url: http://vault.vault.svc.cluster.local:8200/v1/auth/jwt/login
          method: POST
          body:
            expression: |
              '{"role":"authorino","jwt":"' + request.headers.authorization.split(' ')[1] + '"}'
          contentType: application/json
        priority: 0
      vault_team_secret:
        http:
          urlExpression: |
            'http://vault.vault.svc.cluster.local:8200/v1/secret/data/mcp-gateway/teams/'
            + (auth.identity.groups.exists(g, g == 'team-a-leads') ? 'team-a-leads'
            : auth.identity.groups.exists(g, g == 'team-a-ops') ? 'team-a-ops'
            : 'team-a-developers')
          headers:
            X-Vault-Token:
              expression: auth.metadata.vault_token.auth.client_token
        priority: 1
    authorization:
      group-tool-access:
        patternMatching:
          patterns:
            - predicate: >-
                (auth.identity.groups.exists(g, g == 'team-a-developers')
                && request.headers['x-mcp-toolname'] in ['greet', 'time', 'headers'])
                || (auth.identity.groups.exists(g, g == 'team-a-ops')
                && request.headers['x-mcp-toolname'] in ['add_tool', 'slow'])
                || (auth.identity.groups.exists(g, g == 'team-a-leads')
                && request.headers['x-mcp-toolname'] in ['add_tool', 'greet', 'headers', 'slow', 'time'])
    response:
      success:
        headers:
          x-team-credential:
            plain:
              expression: auth.metadata.vault_team_secret.data.data.api_key
      unauthenticated:
        body:
          value: |
            {"error":"Unauthorized","message":"Authentication required."}
      unauthorized:
        body:
          value: |
            {"error":"Forbidden","message":"You do not have access to this tool."}
