apiVersion: v1
kind: Service
metadata:
  name: team-a-gateway-tls-np
  namespace: team-a
spec:
  type: NodePort
  selector:
    gateway.networking.k8s.io/gateway-name: team-a-gateway
  ports:
    - name: mcp-https
      port: 8443
      targetPort: 8443
      nodePort: 30443
