apiVersion: mcp.x-k8s.io/v1alpha1
kind: MCPServer
metadata:
  name: test-server-a2
  namespace: team-a
  annotations:
    mcp.x-k8s.io/gateway-ref: team-a/team-a-gateway
spec:
  source:
    type: ContainerImage
    containerImage:
      ref: ghcr.io/kuadrant/mcp-gateway/test-server2:latest
  config:
    port: 9090
    path: /mcp
    env:
      - name: MCP_TRANSPORT
        value: http
      - name: PORT
        value: "9090"
  runtime:
    security:
      securityContext:
        runAsNonRoot: false
