apiVersion: v1
kind: ConfigMap
metadata:
  name: realm-import
  namespace: keycloak
data:
  realm-import.json: |
    {
      "id": "mcp",
      "realm": "mcp",
      "enabled": true,
      "accessTokenLifespan": 1800,
      "clients": [
        {
          "clientId": "mcp-gateway",
          "publicClient": false,
          "secret": "secret",
          "standardFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": true,
          "attributes": {
            "standard.token.exchange.enabled": "true"
          },
          "defaultClientScopes": [
            "roles"
          ],
          "optionalClientScopes": [
            "groups",
            "profile"
          ]
        }
      ],
      "clientScopes": [
        {
          "name": "groups",
          "protocol": "openid-connect",
          "attributes": {
            "display.on.consent.screen": "false",
            "include.in.token.scope": "true"
          },
          "protocolMappers": [
            {
              "name": "groups",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-group-membership-mapper",
              "config": {
                "claim.name": "groups",
                "full.path": "false",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "userinfo.token.claim": "true"
              }
            }
          ]
        },
        {
          "name": "roles",
          "description": "OpenID Connect scope for add user roles to the access token",
          "protocol": "openid-connect",
          "attributes": {
            "include.in.token.scope": "false",
            "display.on.consent.screen": "true"
          },
          "protocolMappers": [
            {
              "name": "realm roles",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-realm-role-mapper",
              "consentRequired": false,
              "config": {
                "introspection.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "realm_access.roles",
                "jsonType.label": "String",
                "multivalued": "true"
              }
            },
            {
              "name": "client roles",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-client-role-mapper",
              "consentRequired": false,
              "config": {
                "introspection.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "resource_access.${client_id}.roles",
                "jsonType.label": "String",
                "multivalued": "true"
              }
            },
            {
              "name": "audience resolve",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-resolve-mapper",
              "consentRequired": false,
              "config": {
                "introspection.token.claim": "true",
                "access.token.claim": "true"
              }
            }
          ]
        }
      ],
      "defaultDefaultClientScopes": [
        "roles"
      ],
      "defaultOptionalClientScopes": [
        "groups"
      ]
    }
