apiVersion: v1
kind: Service
metadata:
  name: team-a-gateway-np
  namespace: team-a
spec:
  type: NodePort
  selector:
    gateway.networking.k8s.io/gateway-name: team-a-gateway
  ports:
    - name: mcp-http
      port: 8080
      targetPort: 8080
      nodePort: 30080
