apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: vllm-20b
  namespace: gpt-oss
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/genai-asset: "true"
  annotations:
    openshift.io/display-name: GPT-OSS-20B Model
spec:
  predictor:
    model:
      modelFormat:
        name: vLLM
        version: "1"
      runtime: vllm-cuda129-20b-runtime
      storageUri: pvc://gpt-oss-20b-models/gpt-oss-20b
